version: '2'
services:
  wildfly:
    image: uvms/wildfly-release:3.9.0
    container_name: wildfly
    ports:
     - "29990:9990"
     - "28787:8787"
     - "28080:8080"
     - "28443:8443"
    volumes:
     - /app/logs:/app/logs
     - /opt/jboss/wildfly/standalone/log:/opt/jboss/wildfly/standalone/log
    depends_on:
     - postgres
     - activemq
    links:
     - postgres
     - activemq
    command: ["/opt/jboss/start.sh", "/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-uvms.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]
  postgres:
    image: uvms/postgres-release:3.9.0
    container_name: postgres
    ports: 
     - "25432:5432"
  activemq:
    image: uvms/activemq:3.9.0
    container_name: activemq
    ports:
     - "18161:8161"
     - "61616:61616"
